[package]
name = "positioned-io"
version = "0.3.0" # remember to update html_root_url and readme
authors = ["Dave Vasilevsky <dave@vasilevsky.ca>", "Niklas Fiekas <niklas.fiekas@backscattering.de>"]
description = "Reading and writing at an offset"
keywords = ["read", "offset", "pread", "pwrite", "endian"]
categories = ["filesystem", "os"]
license = "MIT"
repository = "https://github.com/vasi/positioned-io"
readme = "README.md"

[dependencies]
byteorder = "1.4"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["basetsd", "minwindef", "handleapi", "fileapi", "sysinfoapi", "memoryapi", "winnt"] }

[dev-dependencies]
quickcheck = "0.8"
rand = "0.6"
tempfile = "3.0"

[badges]
travis-ci = { repository = "vasi/positioned-io", branch = "master" }
appveyor = { repository = "niklasf/positioned-io" }
